# GitHub Sponsors and funding platforms
# 在 https://github.com/sponsors 申请开通后，取消注释下一行
github: [theneoai]

# 其他平台（可选）
# patreon: theneoai
# open_collective: awesome-skills
# ko_fi: theneoai
# custom: ["https://buymeacoffee.com/theneoai"]
