#!/bin/bash
#
# Create manifest repository for managing multiple Gerrit repositories
# Usage: ./create-manifest-repo.sh <manifest-name> <repo-list-file>

set -e

MANIFEST_NAME=${1:-"default-manifest"}
REPO_LIST_FILE=${2:-""}
GERRIT_HOST=${GERRIT_HOST:-"localhost"}
GERRIT_PORT=${GERRIT_PORT:-"29418"}
GERRIT_WEB_PORT=${GERRIT_WEB_PORT:-"8080"}
GERRIT_USER=${GERRIT_USER:-"admin"}

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if repo list file exists
if [[ -n "$REPO_LIST_FILE" && ! -f "$REPO_LIST_FILE" ]]; then
    log_error "Repository list file not found: $REPO_LIST_FILE"
    exit 1
fi

# Create manifest repository name (typically ends with -manifest)
if [[ ! "$MANIFEST_NAME" == *-manifest ]]; then
    MANIFEST_REPO="${MANIFEST_NAME}-manifest"
else
    MANIFEST_REPO="$MANIFEST_NAME"
fi

log_info "Creating manifest repository: $MANIFEST_REPO"

# Create the manifest repository via SSH
ssh -p $GERRIT_PORT $GERRIT_USER@$GERRIT_HOST gerrit create-project "$MANIFEST_REPO" --empty-commit 2>/dev/null || {
    log_warn "Repository may already exist or SSH connection failed"
}

# Create temporary directory for manifest setup
TEMP_DIR=$(mktemp -d)
cd "$TEMP_DIR"

# Clone the manifest repository
MANIFEST_URL="http://${GERRIT_HOST}:${GERRIT_WEB_PORT}/${MANIFEST_REPO}"
log_info "Cloning manifest repository from $MANIFEST_URL"

git clone "$MANIFEST_URL" .
git config user.name "Manifest Admin"
git config user.email "admin@local"

# Create default.xml manifest file
cat > default.xml << 'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <remote name="origin"
          fetch="http://GERRIT_HOST:GERRIT_WEB_PORT/"
          review="http://GERRIT_HOST:GERRIT_WEB_PORT/" />
  
  <default remote="origin"
           revision="main"
           sync-j="4" />

  <!-- Projects will be added here -->

</manifest>
EOF

# Replace placeholders with actual values
sed -i.bak "s/GERRIT_HOST/$GERRIT_HOST/g" default.xml
sed -i.bak "s/GERRIT_WEB_PORT/$GERRIT_WEB_PORT/g" default.xml
rm -f default.xml.bak

# If repo list file provided, add projects
if [[ -n "$REPO_LIST_FILE" ]]; then
    log_info "Adding projects from $REPO_LIST_FILE"
    
    # Read repo list and add to manifest
    while IFS= read -r repo_name || [[ -n "$repo_name" ]]; do
        # Skip empty lines and comments
        [[ -z "$repo_name" || "$repo_name" =~ ^[[:space:]]*# ]] && continue
        
        # Trim whitespace
        repo_name=$(echo "$repo_name" | xargs)
        
        # Create project entry
        project_path="${repo_name}"
        
        # Add to manifest
        sed -i.bak "/<!-- Projects will be added here -->/a\\
  <project path=\"$project_path\" name=\"$repo_name\" />" default.xml
        
        log_info "Added project: $repo_name"
    done < "$REPO_LIST_FILE"
    
    rm -f default.xml.bak
fi

# Create additional manifest files
cat > README.md << EOF
# $MANIFEST_REPO

Manifest repository for managing multiple Gerrit repositories using the repo tool.

## Usage

### Initialize all repositories

\`\`\`bash
mkdir workspace
cd workspace
repo init -u http://${GERRIT_HOST}:${GERRIT_WEB_PORT}/${MANIFEST_REPO}
repo sync
\`\`\`

### Sync all repositories

\`\`\`bash
repo sync
\`\`\`

### Create topic branch across all repos

\`\`\`bash
repo start my-topic --all
\`\`\`

## Repository Structure

This manifest manages the following repositories:

EOF

# Add repo list to README
if [[ -n "$REPO_LIST_FILE" ]]; then
    while IFS= read -r repo_name || [[ -n "$repo_name" ]]; do
        [[ -z "$repo_name" || "$repo_name" =~ ^[[:space:]]*# ]] && continue
        repo_name=$(echo "$repo_name" | xargs)
        echo "- $repo_name" >> README.md
    done < "$REPO_LIST_FILE"
else
    echo "(No repositories configured yet)" >> README.md
fi

# Create groups configuration for permissions
cat > groups.json << EOF
{
  "groups": [
    {
      "name": "Maintainers",
      "description": "Project maintainers with full access",
      "members": []
    },
    {
      "name": "Developers",
      "description": "Regular developers with submit access",
      "members": []
    },
    {
      "name": "Reviewers",
      "description": "Code reviewers",
      "members": []
    }
  ]
}
EOF

# Commit and push
git add -A
git commit -m "Initial manifest setup for $MANIFEST_NAME

- Created default.xml with project configuration
- Added README.md with usage instructions
- Created groups.json for permission management

Generated by gerrit-permission-manager skill"

git push origin HEAD:refs/heads/main 2>/dev/null || git push origin HEAD:refs/heads/master 2>/dev/null || {
    log_warn "Push failed, attempting force push to master"
    git push -f origin HEAD:refs/heads/master
}

log_info "Manifest repository created successfully!"
log_info "URL: $MANIFEST_URL"
log_info ""
log_info "To use this manifest:"
log_info "  mkdir workspace && cd workspace"
log_info "  repo init -u $MANIFEST_URL"
log_info "  repo sync"

# Cleanup
cd -
rm -rf "$TEMP_DIR"
